In [2]:
import pandas as pd

In [3]:
data = pd.read_csv('epidemiology1.csv')
# Tipo de dato de la fecha
data['date'] = pd.to_datetime(data['date'], format='%d/%m/%Y')

"""!!!!!!!!"""
# Rellenamos NA con 0
data['new_confirmed'].fillna(0, inplace=True)
data['new_recovered'].fillna(0, inplace=True)
data['new_deceased'].fillna(0, inplace=True)
"""!!!!!!!!"""

# Solo columnas necesarioas
cleaned_data = data[['date', 'new_confirmed', 'new_recovered', 'new_deceased']]

In [3]:
cleaned_data

              date  new_confirmed  new_recovered  new_deceased
0       2020-01-01            0.0            0.0           0.0
1       2020-01-02            0.0            0.0           0.0
2       2020-01-03            0.0            0.0           0.0
3       2020-01-04            0.0            0.0           0.0
4       2020-01-05            0.0            0.0           0.0
...            ...            ...            ...           ...
1048570 2021-01-09            3.0            0.0           0.0
1048571 2021-01-10            4.0            0.0           0.0
1048572 2021-01-11            0.0            0.0           0.0
1048573 2021-01-12            5.0            0.0           0.0
1048574 2021-01-13            0.0            0.0           0.0

[1048575 rows x 4 columns]

In [4]:
# cleaned_data.to_csv('cleaned_epidemiology_data.csv', index=False)